sudo: required
services: 
  - docker

before_install:
  - docker build -t gniwll/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run gniwll/react-test npm test -- --coverage

after_success:
  - docker build -t gniwll/multi-client ./client
  - docker build -t gniwll/multi-nginx ./nginx
  - docker build -t gniwll/multi-server ./server
  - docker build -t gniwll/multi-worker ./worker
  
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push gniwll/multi-client
  - docker push gniwll/multi-nginx
  - docker push gniwll/multi-server
  - docker push gniwll/multi-worker
